const keys = [
  {
    attribute: 'Backquote',
    english: '`',
    englishshift: '~',
    russian: 'ё',
    russianshift: 'ё',
    aux: false,
    isTextArea: true,
    row: 0,
  },
  {
    attribute: 'Digit1',
    english: '1',
    englishshift: '!',
    russian: '1',
    russianshift: '!',
    aux: false,
    isTextArea: true,
    row: 0,
  },
  {
    attribute: 'Digit2',
    english: '2',
    englishshift: '@',
    russian: '2',
    russianshift: '"',
    aux: false,
    isTextArea: true,
    row: 0,
  },
  {
    attribute: 'Digit3',
    english: '3',
    englishshift: '#',
    russian: '3',
    russianshift: '№',
    aux: false,
    isTextArea: true,
    row: 0,
  },
  {
    attribute: 'Digit4',
    english: '4',
    englishshift: '$',
    russian: '4',
    russianshift: ';',
    aux: false,
    isTextArea: true,
    row: 0,
  },
  {
    attribute: 'Digit5',
    english: '5',
    englishshift: '%',
    russian: '5',
    russianshift: '%',
    aux: false,
    isTextArea: true,
    row: 0,
  },
  {
    attribute: 'Digit6',
    english: '6',
    englishshift: '^',
    russian: '6',
    russianshift: ':',
    aux: false,
    isTextArea: true,
    row: 0,
  },
  {
    attribute: 'Digit7',
    english: '7',
    englishshift: '&',
    russian: '7',
    russianshift: '?',
    aux: false,
    isTextArea: true,
    row: 0,
  },
  {
    attribute: 'Digit8',
    english: '8',
    englishshift: '*',
    russian: '8',
    russianshift: '*',
    aux: false,
    isTextArea: true,
    row: 0,
  },
  {
    attribute: 'Digit9',
    english: '9',
    englishshift: '(',
    russian: '9',
    russianshift: '(',
    aux: false,
    isTextArea: true,
    row: 0,
  },
  {
    attribute: 'Digit0',
    english: '0',
    englishshift: ')',
    russian: '0',
    russianshift: ')',
    aux: false,
    isTextArea: true,
    row: 0,
  },
  {
    attribute: 'Minus',
    english: '-',
    englishshift: '_',
    russian: '-',
    russianshift: '_',
    aux: false,
    isTextArea: true,
    row: 0,
  },
  {
    attribute: 'Equal',
    english: '=',
    englishshift: '+',
    russian: '=',
    russianshift: '+',
    aux: false,
    isTextArea: true,
    row: 0,
  },
  {
    attribute: 'Backspace',
    english: 'Backspace',
    englishshift: 'Backspace',
    russian: 'Backspace',
    russianshift: 'Backspace',
    aux: true,
    isTextArea: false,
    row: 0,
  },
  {
    attribute: 'Tab',
    english: 'Tab',
    englishshift: 'Tab',
    russian: 'Tab',
    russianshift: 'Tab',
    aux: true,
    isTextArea: false,
    row: 1,
  },
  {
    attribute: 'KeyQ',
    english: 'q',
    englishshift: 'q',
    russian: 'й',
    russianshift: 'й',
    aux: false,
    isTextArea: true,
    row: 1,
  },
  {
    attribute: 'KeyW',
    english: 'w',
    englishshift: 'w',
    russian: 'ц',
    russianshift: 'ц',
    aux: false,
    isTextArea: true,
    row: 1,
  },
  {
    attribute: 'KeyE',
    english: 'e',
    englishshift: 'e',
    russian: 'у',
    russianshift: 'у',
    aux: false,
    isTextArea: true,
    row: 1,
  },
  {
    attribute: 'KeyR',
    english: 'r',
    englishshift: 'r',
    russian: 'к',
    russianshift: 'к',
    aux: false,
    isTextArea: true,
    row: 1,
  },
  {
    attribute: 'KeyT',
    english: 't',
    englishshift: 't',
    russian: 'е',
    russianshift: 'е',
    aux: false,
    isTextArea: true,
    row: 1,
  },
  {
    attribute: 'KeyY',
    english: 'y',
    englishshift: 'y',
    russian: 'н',
    russianshift: 'н',
    aux: false,
    isTextArea: true,
    row: 1,
  },
  {
    attribute: 'KeyU',
    english: 'u',
    englishshift: 'u',
    russian: 'г',
    russianshift: 'г',
    aux: false,
    isTextArea: true,
    row: 1,
  },
  {
    attribute: 'KeyI',
    english: 'i',
    englishshift: 'i',
    russian: 'ш',
    russianshift: 'ш',
    aux: false,
    isTextArea: true,
    row: 1,
  },
  {
    attribute: 'KeyO',
    english: 'o',
    englishshift: 'o',
    russian: 'щ',
    russianshift: 'щ',
    aux: false,
    isTextArea: true,
    row: 1,
  },
  {
    attribute: 'KeyP',
    english: 'p',
    englishshift: 'p',
    russian: 'з',
    russianshift: 'з',
    aux: false,
    isTextArea: true,
    row: 1,
  },
  {
    attribute: 'BracketLeft',
    english: '[',
    englishshift: '{',
    russian: 'х',
    russianshift: 'х',
    aux: false,
    isTextArea: true,
    row: 1,
  },
  {
    attribute: 'BracketRight',
    english: ']',
    englishshift: '}',
    russian: 'ъ',
    russianshift: 'ъ',
    aux: false,
    isTextArea: true,
    row: 1,
  },

  {
    attribute: 'Delete',
    english: 'Del',
    englishshift: 'Del',
    russian: 'Del',
    russianshift: 'Del',
    aux: true,
    isTextArea: false,
    row: 1,
  },
  {
    attribute: 'CapsLock',
    english: 'CapsLock',
    englishshift: 'CapsLock',
    russian: 'CapsLock',
    russianshift: 'CapsLock',
    aux: true,
    isTextArea: false,
    row: 2,
  },
  {
    attribute: 'KeyA',
    english: 'a',
    englishshift: 'a',
    russian: 'ф',
    russianshift: 'ф',
    aux: false,
    isTextArea: true,
    row: 2,
  },

  {
    attribute: 'KeyS',
    english: 's',
    englishshift: 's',
    russian: 'ы',
    russianshift: 'ы',
    aux: false,
    isTextArea: true,
    row: 2,
  },
  {
    attribute: 'KeyD',
    english: 'd',
    englishshift: 'd',
    russian: 'в',
    russianshift: 'в',
    aux: false,
    isTextArea: true,
    row: 2,
  },
  {
    attribute: 'KeyF',
    english: 'f',
    englishshift: 'f',
    russian: 'а',
    russianshift: 'а',
    aux: false,
    isTextArea: true,
    row: 2,
  },
  {
    attribute: 'KeyG',
    english: 'g',
    englishshift: 'g',
    russian: 'п',
    russianshift: 'п',
    aux: false,
    isTextArea: true,
    row: 2,
  },

  {
    attribute: 'KeyH',
    english: 'h',
    englishshift: 'h',
    russian: 'р',
    russianshift: 'р',
    aux: false,
    isTextArea: true,
    row: 2,
  },
  {
    attribute: 'KeyJ',
    english: 'j',
    englishshift: 'j',
    russian: 'о',
    russianshift: 'о',
    aux: false,
    isTextArea: true,
    row: 2,
  },
  {
    attribute: 'KeyK',
    english: 'k',
    englishshift: 'k',
    russian: 'л',
    russianshift: 'л',
    aux: false,
    isTextArea: true,
    row: 2,
  },
  {
    attribute: 'KeyL',
    english: 'l',
    englishshift: 'l',
    russian: 'д',
    russianshift: 'д',
    aux: false,
    isTextArea: true,
    row: 2,
  },
  {
    attribute: 'Semicolon',
    english: ';',
    englishshift: ':',
    russian: 'ж',
    russianshift: 'ж',
    aux: false,
    isTextArea: true,
    row: 2,
  },
  {
    attribute: 'Quote',
    english: "'",
    englishshift: '"',
    russian: 'э',
    russianshift: 'э',
    aux: false,
    isTextArea: true,
    row: 2,
  },
  {
    attribute: 'Backslash',
    english: '\\',
    englishshift: '|',
    russian: '\\',
    russianshift: '/',
    aux: false,
    isTextArea: true,
    row: 2,
  },
  {
    attribute: 'Enter',
    english: 'Enter',
    englishshift: 'Enter',
    russian: 'Enter',
    russianshift: 'Enter',
    aux: true,
    isTextArea: false,
    row: 2,
  },
  {
    attribute: 'ShiftLeft',
    english: 'Shift',
    englishshift: 'Shift',
    russian: 'Shift',
    russianshift: 'Shift',
    aux: true,
    isTextArea: false,
    row: 3,
  },
  {
    attribute: 'KeyZ',
    english: 'z',
    englishshift: 'z',
    russian: 'я',
    russianshift: 'я',
    aux: false,
    isTextArea: true,
    row: 3,
  },
  {
    attribute: 'KeyX',
    english: 'x',
    englishshift: 'x',
    russian: 'ч',
    russianshift: 'ч',
    aux: false,
    isTextArea: true,
    row: 3,
  },

  {
    attribute: 'KeyC',
    english: 'c',
    englishshift: 'c',
    russian: 'с',
    russianshift: 'с',
    aux: false,
    isTextArea: true,
    row: 3,
  },
  {
    attribute: 'KeyV',
    english: 'v',
    englishshift: 'v',
    russian: 'м',
    russianshift: 'м',
    aux: false,
    isTextArea: true,
    row: 3,
  },

  {
    attribute: 'KeyB',
    english: 'b',
    englishshift: 'b',
    russian: 'и',
    russianshift: 'и',
    aux: false,
    isTextArea: true,
    row: 3,
  },

  {
    attribute: 'KeyN',
    english: 'n',
    englishshift: 'n',
    russian: 'т',
    russianshift: 'т',
    aux: false,
    isTextArea: true,
    row: 3,
  },

  {
    attribute: 'KeyM',
    english: 'm',
    englishshift: 'm',
    russian: 'ь',
    russianshift: 'ь',
    aux: false,
    isTextArea: true,
    row: 3,
  },

  {
    attribute: 'Comma',
    english: ',',
    englishshift: '<',
    russian: 'б',
    russianshift: 'б',
    aux: false,
    isTextArea: true,
    row: 3,
  },

  {
    attribute: 'Period',
    english: '.',
    englishshift: '>',
    russian: 'ю',
    russianshift: 'ю',
    aux: false,
    isTextArea: true,
    row: 3,
  },

  {
    attribute: 'Slash',
    english: '/',
    englishshift: '?',
    russian: '.',
    russianshift: ',',
    aux: false,
    isTextArea: true,
    row: 3,
  },

  {
    attribute: 'ArrowUp',
    english: '\u2191',
    englishshift: '\u2191',
    russian: '\u2191',
    russianshift: '\u2191',
    aux: true,
    isTextArea: true,
    row: 3,
  },

  {
    attribute: 'ShiftRight',
    english: 'Shift',
    englishshift: 'Shift',
    russian: 'Shift',
    russianshift: 'Shift',
    aux: true,
    isTextArea: false,
    row: 3,
  },

  {
    attribute: 'ControlLeft',
    english: 'Ctrl',
    englishshift: 'Ctrl',
    russian: 'Ctrl',
    russianshift: 'Ctrl',
    aux: true,
    isTextArea: false,
    row: 4,
  },

  {
    attribute: 'MetaLeft',
    english: 'Win',
    englishshift: 'Win',
    russian: 'Win',
    russianshift: 'Win',
    aux: true,
    isTextArea: false,
    row: 4,
  },

  {
    attribute: 'AltLeft',
    english: 'Alt',
    englishshift: 'Alt',
    russian: 'Alt',
    russianshift: 'Alt',
    aux: true,
    isTextArea: false,
    row: 4,
  },

  {
    attribute: 'Space',
    english: ' ',
    englishshift: ' ',
    russian: ' ',
    russianshift: ' ',
    aux: false,
    isTextArea: false,
    row: 4,
  },

  {
    attribute: 'AltRight',
    english: 'Alt',
    englishshift: 'Alt',
    russian: 'Alt',
    russianshift: 'Alt',
    aux: true,
    isTextArea: false,
    row: 4,
  },
  {
    attribute: 'ArrowLeft',
    english: '\u2190',
    englishshift: '\u2190',
    russian: '\u2190',
    russianshift: '\u2190',
    aux: true,
    isTextArea: true,
    row: 4,
  },

  {
    attribute: 'ArrowDown',
    english: '\u2193',
    englishshift: '\u2193',
    russian: '\u2193',
    russianshift: '\u2193',
    aux: true,
    isTextArea: true,
    row: 4,
  },

  {
    attribute: 'ArrowRight',
    english: '\u2192',
    englishshift: '\u2192',
    russian: '\u2192',
    russianshift: '\u2192',
    aux: true,
    isTextArea: true,
    row: 4,
  },

  {
    attribute: 'ControlRight',
    english: 'Ctrl',
    englishshift: 'Ctrl',
    russian: 'Ctrl',
    russianshift: 'Ctrl',
    aux: true,
    isTextArea: false,
    row: 4,
  },
];
export default keys;
